# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19625f3e041d7eb410a89ad75d99ae245ebaf750adbf2e35b3f80f66d22fe45bec5baaf9c8644bd23fb4b8a625588164ca4bf0ec072bb6d89422f215079d13ed

test:
  secret_key_base: a487671635e5ac46df4d955b51ffc3fd73a766d1f703e58ff9443e3e598ce26bac428c3d87b6e8c63a39d17c9589d01d63b311d2f279c53e88758905baeb5c00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
